### PR TITLE
[Added] Ability to pass in gradient type

### PR DESCRIPTION
**Pull request by nfourtythree**

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hi Nathaniel, thanks for this contribution I really like it.

I wonder if we could improve the way we define the type. It bothers me a bit to split the definition of a gradient in two different options.

We could:
- either support an object definition for a gradient with a `type` key
- or provide an array in your `types` option (defaulting to `['linear']`) and generate all gradient for all provided types.

What do you think?

**Comment by nfourtythree** [comment]
Hey, no worries always trying to help out where I can!

Yea I agree my pull request isn't the most elegant way of doing things. I was trying to make sure that the changes I made wouldn't cause any breaking changes/errors if people using the plugin updated the package.

I like option one, it kind of makes the most sense especially when it comes to usage/readability in the config. My only thing is, as above, this could cause breaking changes for people unless we keep the ability to pass either the current format (maybe deprecating it) and the new format.

The only issue I see with option 2 is really that the first param in a radial gradient can be quite different to a linear gradient and could cause some erroneous CSS to be output which wouldn't be ideal.

What are your thoughts?

**Comment by lorisleiva** [comment]
I agree, I prefer option 1. We can very easily make this a non-breaking change by supporting both data structures.

If the user provides an array, it is considered as a linear gradient.

If the user provides an object, they have to provide the `colors` key as an array (which can have an angle has a first item as currently supported) but they can also provide the `type` key which default to `linear`.

I like this approach as it also opens up more options for the future by just adding keys to this object (very much like `props` in VueJs).

Are you confortable writing these changes within this PR or would you like me to merge this and do the changes afterwards?

Thanks again for your help on this :)

**Comment by nfourtythree** [comment]
@lorisleiva have committed a couple of updates. Let me know what you think 👍

**Comment by lorisleiva** [comment]
@nfourtythree That's much better thank you. I'll create a new release very soon.

**Comment by nfourtythree** [comment]
@lorisleiva great news! If you could publish it to npm that would be great, using it in a project I am currently working on!

**Comment by lorisleiva** [comment]
@nfourtythree No problem, I'm just writing a few tests to make sure everything is working. Typically I had to change `isObject` by `isPlainObject` because the first one considers arrays to be objects.

screenshot 2018-11-06 at 11 07 55

**Comment by lorisleiva** [comment]
@nfourtythree All done and published. Let me know if everything works fine on your current project 🙂

**Pull request merged**
